import type { GearCubeState } from '@gearcube/core';

export interface ExactDistanceFixture {
  readonly serializedState: string;
  readonly expectedExactDistance: number;
}

/**
 * Deterministic exact canonical distance fixtures for depths 1..8.
 * Generated by the independent test-only BFS distance oracle over @gearcube/core.
 */
export const EXACT_DISTANCE_FIXTURES: readonly ExactDistanceFixture[] = [
  {
    serializedState: 'C:6|X:1.0|Y:3.1|Z:1.0',
    expectedExactDistance: 1,
  },
  {
    serializedState: 'C:0|X:0.0|Y:2.2|Z:0.0',
    expectedExactDistance: 2,
  },
  {
    serializedState: 'C:6|X:1.0|Y:1.0|Z:1.0',
    expectedExactDistance: 3,
  },
  {
    serializedState: 'C:12|X:2.0|Y:0.0|Z:0.1',
    expectedExactDistance: 4,
  },
  {
    serializedState: 'C:6|X:1.0|Y:1.0|Z:3.2',
    expectedExactDistance: 5,
  },
  {
    serializedState: 'C:19|X:0.1|Y:2.0|Z:0.2',
    expectedExactDistance: 6,
  },
  {
    serializedState: 'C:6|X:3.2|Y:1.0|Z:3.2',
    expectedExactDistance: 7,
  },
  {
    serializedState: 'C:0|X:3.2|Y:1.1|Z:2.2',
    expectedExactDistance: 8,
  },
] as const;
