/**
 * @file transition-data.ts
 * @description Checked-in deterministic frozen canonical transition lookup tables.
 * @internal
 */

import type {
  CornerConfiguration,
  Direction,
  Face,
  SliceGearPhase,
  SlicePermutationClass,
} from './values.js';

export type InternalSliceName = 'X' | 'Y' | 'Z';

/**
 * Precomputed corner configuration S_4 transpositions.
 * Maps Face -> current CornerConfiguration -> next CornerConfiguration.
 */
export const CORNER_TRANSITIONS: Readonly<
  Record<Face, readonly CornerConfiguration[]>
> = Object.freeze({
  U: Object.freeze([
    6, 7, 12, 13, 18, 19,
    0, 1, 14, 15, 20, 21,
    2, 3, 8, 9, 22, 23,
    4, 5, 10, 11, 16, 17,
  ] as const),
  D: Object.freeze([
    6, 7, 12, 13, 18, 19,
    0, 1, 14, 15, 20, 21,
    2, 3, 8, 9, 22, 23,
    4, 5, 10, 11, 16, 17,
  ] as const),
  F: Object.freeze([
    14, 20, 8, 22, 10, 16,
    12, 18, 2, 23, 4, 17,
    6, 19, 0, 21, 5, 11,
    7, 13, 1, 15, 3, 9,
  ] as const),
  B: Object.freeze([
    14, 20, 8, 22, 10, 16,
    12, 18, 2, 23, 4, 17,
    6, 19, 0, 21, 5, 11,
    7, 13, 1, 15, 3, 9,
  ] as const),
  R: Object.freeze([
    21, 15, 23, 9, 17, 11,
    19, 13, 22, 3, 16, 5,
    18, 7, 20, 1, 10, 4,
    12, 6, 14, 0, 8, 2,
  ] as const),
  L: Object.freeze([
    21, 15, 23, 9, 17, 11,
    19, 13, 22, 3, 16, 5,
    18, 7, 20, 1, 10, 4,
    12, 6, 14, 0, 8, 2,
  ] as const),
});

/**
 * Phase twist delta for each edge slice on canonical moves.
 * Increment is applied modulo 3.
 */
export const SLICE_DELTA_PHASES: Readonly<
  Record<
    Face,
    Readonly<Record<Direction, Readonly<Record<InternalSliceName, SliceGearPhase>>>>
  >
> = Object.freeze({
  U: Object.freeze({
    CW: Object.freeze({ X: 0, Y: 1, Z: 0 }),
    CCW: Object.freeze({ X: 0, Y: 2, Z: 0 }),
  }),
  D: Object.freeze({
    CW: Object.freeze({ X: 0, Y: 2, Z: 0 }),
    CCW: Object.freeze({ X: 0, Y: 1, Z: 0 }),
  }),
  F: Object.freeze({
    CW: Object.freeze({ X: 0, Y: 0, Z: 1 }),
    CCW: Object.freeze({ X: 0, Y: 0, Z: 2 }),
  }),
  B: Object.freeze({
    CW: Object.freeze({ X: 0, Y: 0, Z: 2 }),
    CCW: Object.freeze({ X: 0, Y: 0, Z: 1 }),
  }),
  R: Object.freeze({
    CW: Object.freeze({ X: 1, Y: 0, Z: 0 }),
    CCW: Object.freeze({ X: 2, Y: 0, Z: 0 }),
  }),
  L: Object.freeze({
    CW: Object.freeze({ X: 2, Y: 0, Z: 0 }),
    CCW: Object.freeze({ X: 1, Y: 0, Z: 0 }),
  }),
});

/**
 * Permutation class transition for edge slices (X, Y, Z).
 * Maps Face -> Direction -> Slice -> CornerConfiguration -> current Class -> next Class.
 */
export const SLICE_K_TRANSITIONS: Readonly<
  Record<
    Face,
    Readonly<
      Record<
        Direction,
        Readonly<
          Record<
            InternalSliceName,
            readonly (readonly SlicePermutationClass[])[]
          >
        >
      >
    >
  >
> = Object.freeze({
  U: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
    }),
  }),
  D: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
    }),
  }),
  F: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
    }),
  }),
  B: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
    }),
  }),
  R: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
      ] as const),
    }),
  }),
  L: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
      ] as const),
    }),
  }),
});
