/**
 * @file transition-data.ts
 * @description Checked-in deterministic frozen canonical transition lookup tables.
 * @remarks
 * This module is the static-data boundary for the canonical move algebra. Its
 * values are the accepted reference-normalized tables documented by ADR-0005
 * and checked by exhaustive transition tests; production behavior must not be
 * used to regenerate or hand-tune them.
 *
 * Lookup dimensions are part of the internal contract: face keys use `Face`,
 * corner rows index all 24 `CornerConfiguration` values, and slice rows retain
 * the `InternalSliceName` and `Direction` ordering. The transition tests cover
 * closure, inverse moves, 12-repeat identity, and equivalence with the
 * independent normalization oracle.
 * @internal
 */

import type {
  CornerConfiguration,
  Direction,
  Face,
  SliceGearPhase,
  SlicePermutationClass,
} from './values.js';

export type InternalSliceName = 'X' | 'Y' | 'Z';

/**
 * Precomputed corner-configuration transitions for canonical face moves.
 *
 * The first key is the moved face; each row then maps a current
 * `CornerConfiguration` index in `[0..23]` to the next configuration index.
 */
export const CORNER_TRANSITIONS: Readonly<
  Record<Face, readonly CornerConfiguration[]>
> = Object.freeze({
  U: Object.freeze([
    6, 7, 12, 13, 18, 19,
    0, 1, 14, 15, 20, 21,
    2, 3, 8, 9, 22, 23,
    4, 5, 10, 11, 16, 17,
  ] as const),
  D: Object.freeze([
    6, 7, 12, 13, 18, 19,
    0, 1, 14, 15, 20, 21,
    2, 3, 8, 9, 22, 23,
    4, 5, 10, 11, 16, 17,
  ] as const),
  F: Object.freeze([
    14, 20, 8, 22, 10, 16,
    12, 18, 2, 23, 4, 17,
    6, 19, 0, 21, 5, 11,
    7, 13, 1, 15, 3, 9,
  ] as const),
  B: Object.freeze([
    14, 20, 8, 22, 10, 16,
    12, 18, 2, 23, 4, 17,
    6, 19, 0, 21, 5, 11,
    7, 13, 1, 15, 3, 9,
  ] as const),
  R: Object.freeze([
    21, 15, 23, 9, 17, 11,
    19, 13, 22, 3, 16, 5,
    18, 7, 20, 1, 10, 4,
    12, 6, 14, 0, 8, 2,
  ] as const),
  L: Object.freeze([
    21, 15, 23, 9, 17, 11,
    19, 13, 22, 3, 16, 5,
    18, 7, 20, 1, 10, 4,
    12, 6, 14, 0, 8, 2,
  ] as const),
});

/**
 * Phase-twist delta for each edge slice on canonical moves.
 *
 * The table is indexed by face, direction, and internal slice. The returned
 * `SliceGearPhase` is added modulo 3 while applying the move, so clockwise and
 * counter-clockwise entries are explicit inverses rather than inferred at
 * runtime.
 */
export const SLICE_DELTA_PHASES: Readonly<
  Record<
    Face,
    Readonly<Record<Direction, Readonly<Record<InternalSliceName, SliceGearPhase>>>>
  >
> = Object.freeze({
  U: Object.freeze({
    CW: Object.freeze({ X: 0, Y: 1, Z: 0 }),
    CCW: Object.freeze({ X: 0, Y: 2, Z: 0 }),
  }),
  D: Object.freeze({
    CW: Object.freeze({ X: 0, Y: 2, Z: 0 }),
    CCW: Object.freeze({ X: 0, Y: 1, Z: 0 }),
  }),
  F: Object.freeze({
    CW: Object.freeze({ X: 0, Y: 0, Z: 1 }),
    CCW: Object.freeze({ X: 0, Y: 0, Z: 2 }),
  }),
  B: Object.freeze({
    CW: Object.freeze({ X: 0, Y: 0, Z: 2 }),
    CCW: Object.freeze({ X: 0, Y: 0, Z: 1 }),
  }),
  R: Object.freeze({
    CW: Object.freeze({ X: 1, Y: 0, Z: 0 }),
    CCW: Object.freeze({ X: 2, Y: 0, Z: 0 }),
  }),
  L: Object.freeze({
    CW: Object.freeze({ X: 2, Y: 0, Z: 0 }),
    CCW: Object.freeze({ X: 1, Y: 0, Z: 0 }),
  }),
});

/**
 * Permutation-class transitions for the three edge slices (X, Y, Z).
 *
 * The lookup path is `Face -> Direction -> InternalSliceName ->
 * CornerConfiguration -> current SlicePermutationClass -> next class`. Each
 * innermost row is a four-position permutation for one canonical state index.
 */
export const SLICE_K_TRANSITIONS: Readonly<
  Record<
    Face,
    Readonly<
      Record<
        Direction,
        Readonly<
          Record<
            InternalSliceName,
            readonly (readonly SlicePermutationClass[])[]
          >
        >
      >
    >
  >
> = Object.freeze({
  U: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
    }),
  }),
  D: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
    }),
  }),
  F: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
    }),
  }),
  B: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
        Object.freeze([1, 0, 2, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
    }),
  }),
  R: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
      ] as const),
    }),
  }),
  L: Object.freeze({
    CW: Object.freeze({
      X: Object.freeze([
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
        Object.freeze([3, 0, 1, 2] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
      ] as const),
    }),
    CCW: Object.freeze({
      X: Object.freeze([
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
        Object.freeze([1, 2, 3, 0] as const),
      ] as const),
      Y: Object.freeze([
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
        Object.freeze([0, 2, 1, 3] as const),
      ] as const),
      Z: Object.freeze([
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
        Object.freeze([3, 1, 2, 0] as const),
      ] as const),
    }),
  }),
});
